import {
  DIAGNOSES as D,
  defineMatrix,
  todos,
} from "./support/fault-matrix.mjs";

// Known failures: Factory bugs the recovery redesign (#515) must fix. Each is
// a `todo` with its diagnosis; remove an entry when its case passes.
const known = todos({
  [D.PROJECTION_STOP]: [
    "lost at POST /repos/{owner}/{repo}/labels #1 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/labels #1 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/labels #2 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/labels #2 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues/{number}/labels #1 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues/{number}/labels #1 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues #1 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues #1 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues #2 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues #2 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues/{number}/dependencies/blocked_by #1 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues/{number}/dependencies/blocked_by #1 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues/{number}/sub_issues #1 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues/{number}/sub_issues #1 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues/{number}/sub_issues #2 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues/{number}/sub_issues #2 without an operator stop",
    "unavailable at GET /repos/{owner}/{repo}/issues/{number} #1 without an operator stop",
    "reset at GET /repos/{owner}/{repo}/issues/{number} #1 without an operator stop",
    "unavailable at GET /repos/{owner}/{repo}/labels #1 without an operator stop",
    "reset at GET /repos/{owner}/{repo}/labels #1 without an operator stop",
    "unavailable at GET /repos/{owner}/{repo}/issues #1 without an operator stop",
    "reset at GET /repos/{owner}/{repo}/issues #1 without an operator stop",
    "unavailable at GET /repos/{owner}/{repo}/issues/{number}/dependencies/blocked_by #1 without an operator stop",
    "reset at GET /repos/{owner}/{repo}/issues/{number}/dependencies/blocked_by #1 without an operator stop",
    "unavailable at GET /repos/{owner}/{repo}/issues/{number}/sub_issues #1 without an operator stop",
    "reset at GET /repos/{owner}/{repo}/issues/{number}/sub_issues #1 without an operator stop",
  ],
  [D.CLOSURE_PAUSE]: [
    "lost at POST /repos/{owner}/{repo}/issues/{number}/comments #1 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues/{number}/comments #1 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues/{number}/comments #2 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues/{number}/comments #2 without an operator stop",
    "lost at POST /repos/{owner}/{repo}/issues/{number}/comments #3 without an operator stop",
    "unavailable at POST /repos/{owner}/{repo}/issues/{number}/comments #3 without an operator stop",
    "lost at PATCH /repos/{owner}/{repo}/issues/{number} #1 without an operator stop",
    "unavailable at PATCH /repos/{owner}/{repo}/issues/{number} #1 without an operator stop",
    "lost at PATCH /repos/{owner}/{repo}/issues/{number} #2 without an operator stop",
    "unavailable at PATCH /repos/{owner}/{repo}/issues/{number} #2 without an operator stop",
    "lost at PATCH /repos/{owner}/{repo}/issues/{number} #3 without an operator stop",
    "unavailable at PATCH /repos/{owner}/{repo}/issues/{number} #3 without an operator stop",
    "unavailable at GET /repos/{owner}/{repo}/issues/{number}/comments #1 without an operator stop",
    "reset at GET /repos/{owner}/{repo}/issues/{number}/comments #1 without an operator stop",
  ],
  [D.GIT_PUSH]: [
    "lost at GIT push #1",
    "lost at GIT push #1 without an operator stop",
    "unavailable at GIT push #1",
    "unavailable at GIT push #1 without an operator stop",
    "lost at GIT push #2",
    "lost at GIT push #2 without an operator stop",
    "unavailable at GIT push #2",
    "unavailable at GIT push #2 without an operator stop",
  ],
  [D.GIT_FETCH]: [
    "unavailable at GIT fetch-advertise #1",
    "unavailable at GIT fetch-advertise #1 without an operator stop",
    "reset at GIT fetch-advertise #1",
    "reset at GIT fetch-advertise #1 without an operator stop",
  ],
  [D.PLANNER_STOP]: [
    "lost at model.generateStructured #1 without an operator stop",
    "unavailable at model.generateStructured #1 without an operator stop",
  ],
  [D.PLAN_RECOMPILE]: [
    "crash-before at model.reviewGraph #1",
    "crash-after at model.reviewGraph #1",
    "lost at model.reviewGraph #1",
    "unavailable at model.reviewGraph #1",
  ],
  [D.GRAPH_REVIEW_STOP]: [
    "lost at model.reviewGraph #1 without an operator stop",
    "unavailable at model.reviewGraph #1 without an operator stop",
  ],
  [D.FINAL_REVIEW]: [
    "lost at model.reviewResult #3",
    "lost at model.reviewResult #3 without an operator stop",
    "unavailable at model.reviewResult #3",
    "unavailable at model.reviewResult #3 without an operator stop",
  ],
  [D.START_AMBIGUOUS]: [
    "crash-before at driver.start #1",
    "crash-before at driver.start #1 without an operator stop",
    "crash-after at driver.start #1",
    "crash-after at driver.start #1 without an operator stop",
    "crash-before at driver.start #2",
    "crash-before at driver.start #2 without an operator stop",
    "crash-after at driver.start #2",
    "crash-after at driver.start #2 without an operator stop",
  ],
  [D.START_REPEAT]: [
    "lost at driver.start #1",
    "lost at driver.start #1 without an operator stop",
    "lost at driver.start #2",
    "lost at driver.start #2 without an operator stop",
  ],
  [D.COLLECT_REPEAT]: [
    "crash-after at driver.collect #1",
    "crash-after at driver.collect #1 without an operator stop",
    "lost at driver.collect #1",
    "lost at driver.collect #1 without an operator stop",
    "crash-after at driver.collect #2",
    "crash-after at driver.collect #2 without an operator stop",
    "lost at driver.collect #2",
    "lost at driver.collect #2 without an operator stop",
  ],
});

defineMatrix("regular", known);
